typedef char i8;
typedef short i16;
typedef long i32;
typedef long long i64;
typedef float f32;
typedef double f64;
typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned long u32;
typedef unsigned long long u64;
typedef vector<int> vi;
typedef vector<vi> vvi;
typedef pair<int, int> pii;
typedef map<int, int> mii;
typedef map<int, char> mic;
typedef map<int, string> mis;
typedef map<char, int> mci;
typedef map<char, char> mcc;
typedef map<char, string> mcs;
typedef map<string, int> msi;
typedef map<string, string> mss;
typedef priority_queue prique;
typedef prique<int> Qi;
typedef queue<int> qi;
typedef deque<int> di;
